CREATE TABLE info(
    id SERIAL PRIMERY KEY,
    title VARCHAR (255) UNIQUE NOT NULL,
    description TEXT
);


CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    username VARCHAR (255) NOT NULL,
    password VARCHAR (255) NOT NULL,
    name VARCHAR (255) NOT NULL,
    email VARCHAR (255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);